I've made a change to the `api/package.json` file, adding `"node-cron": "^4.1.0"` to the dependencies. This should resolve the "Error: Cannot find module 'node-cron'" you were seeing.
Next, you'll need to run `npm install` in the `api` directory.